config/routes.rb
Rails.application.routes.draw do

  root "main#index"
  match 'about', to: "main#about", via: :get
  match 'hello', to: "main#hello", via: :get

  get 'main/index'

  resources :categories do
    member do
      get:delete
    end
  end
  
  resources :tasks do
    member do
      get:delete
    end
  end
    
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category,optional:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end


  def destroy
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @tasks =['Fold Laundry','Sweep porch']
  end

  def about
    @created_by ="raj"
    @id=params['id']
    @page=params[:page]
  end

  def hello
    redirect_to(action: 'index')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.order(:position)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task=Task.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end


  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<h2>About</h2>

<p>Description of the Task Manager</p>
<p>Created by <%=@created_by%></p>

app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application to manage a to-do list</p>
<%@tasks.each do |task|%>
  <%=task%>
<%end%>
<br/>
<a href="/tasks/index">Tasks 1  </a><br/>
<%=link_to('Categories',categories_path)%>
<%= link_to('Tasks',tasks_path(page:1))%>
<%= link_to('About',{action:'about',page:5,id:20})%>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<%= link_to('Back to Homepage',{controller:'main',action:'index'})%>
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>
<%=
    link_to('Add New Task',new_task_path)

%>
<div>
  <h2>Tasks</h2>
  <% @tasks.each do |task|%>
    <p><%=task.position%></p>
    <p><%=task.name%></p>
    <p><%=task.completed? ? 'Yes' : 'No'%></p>
    <%= link_to('Show',task_path(task),class:'action show')%>
    <%= link_to('Edit',task_path(task),class:'action show')%>
    <%= link_to('Delete',task_path(task),class:'action show')%>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>


    <%=form_for(@task) do |f|%>

    <%=f.text_field(:name)%><br/>
    <%=f.text_field(:position)%>
    <%=f.check_box(:completed)%>
    <%=f.text_area(:description)%>

    <%=f.submit("Create Task")%>

    <%end%>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

<%= link_to('Back to List',{controller:'tasks',action:'index'})%>



<p><%=@task.name%></p>
<p><%=@task.position%></p>
<p><%=@task.completed? ? 'yes':'no'%></p>

<p><%=@task.description%></p>
<p><%=@task.name%></p>